name: Run STL Script on Push

on:
  push:
    paths:
      - "**.FCStd"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run stl.py
        run: echo ~/stl.py
        # run: echo ''

      - name: Print .FCStd Files
        run: echo "$(date '+%Y-%m-%d %H:%M:%S')" > ~/jawn.txt
