name: Update File with Current Time

on: [push]

jobs:
  update-file:
    runs-on: self-hosted # Make sure this matches your self-hosted runner's label
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update jawn.txt with current time
        run: echo "$(date '+%Y-%m-%d %H:%M:%S')" > ~/jawn.txt
      - name: Update run stl.py
        run: echo `python3 ~/stl.py`
