name: Run Python Script

on: [push]

jobs:
  run-script:
    runs-on: self-hosted # Ensure this matches your self-hosted runner's label
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Run print.py script
      run: python3 ~/print.py
