name: Update File with Current Time

on: [push]

jobs:
  update-file:
    runs-on: self-hosted # Make sure this matches your self-hosted runner's label
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Update jawn.txt with changes in the current push
        run: |
          echo "Changes in push at $(date '+%Y-%m-%d %H:%M:%S'):" >> ~/jawn.txt
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} >> ~/jawn.txt
      - name: Update run stl.py
        run: echo `python3 ~/stl.py`
